In [1]:
import numpy as np
import cv2 

In [2]:
# Face Detectiom
img = cv2.imread('./test/images/friends.jpg')

def display(name, image):
    cv2.imshow(name, image)
    cv2.waitKey(1000)
    cv2.destroyAllWindows()
    
def bakeImage(features, num_detections, circle):
    if circle:
        for hcx,hcy,hh,hw in features:
             center = ((hcx + hcx+hw)//2, (hcy+hh + hcy)//2)
             cv2.circle(img, center, hh//2,(255,255,0))       
    else:
        for hcx,hcy,hh,hw in features:
            p1 = (hcx, hcy)
            p2 = (hcx+hh, hcy+hw)
            cv2.rectangle(img, p1, p2, (255,255,0))
            
    print("DETAILS: prints x and y of head, witdh of face, hieght of face")
    print(features) # prints x and y of head, witdh of face, hieght of face 
    print("DETAILS: prints array length as the number of faces, and the index value is the number of matches")
    print(num_detections) # prints array length as the number of faces, and the index value is the number of matches

display('3GrilsImage', img)

In [4]:
# Load Cascade classifier - frontalface
face_cascade = cv2.CascadeClassifier('./models/haarcascade/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./models/haarcascade/haarcascade_eye.xml')
smile_cascade = cv2.CascadeClassifier('./models/haarcascade/haarcascade_smile.xml')

In [5]:
# apply cascade classifire to an image
# minNeighbors is a threashhold, if a suspected face has less than 4 
# Neighbors then the model is saying there is a low chance of the 
# suspected face is actually a face.
faces, num_dete = face_cascade.detectMultiScale2(img, minNeighbors=8)
bakeImage(faces, num_dete, False)

DETAILS: prints x and y of head, witdh of face, hieght of face
[[128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]
DETAILS: prints array length as the number of faces, and the index value is the number of matches
[104  84  71]


In [6]:
eyes, num_dete = eye_cascade.detectMultiScale2(img, minNeighbors=18)
bakeImage(eyes, num_dete, True)

DETAILS: prints x and y of head, witdh of face, hieght of face
[[ 43  95  25  25]
 [ 39  36  34  34]
 [423 125  23  23]
 [270 109  28  28]
 [182 134  23  23]
 [144 134  24  24]
 [310 111  27  27]
 [451 111  29  29]]
DETAILS: prints array length as the number of faces, and the index value is the number of matches
[30 35 19 82 19 20 43 21]


In [7]:
smiles, num_dete = smile_cascade.detectMultiScale2(img, minNeighbors=100)
bakeImage(smiles, num_dete, False)

DETAILS: prints x and y of head, witdh of face, hieght of face
[[437 156  47  23]
 [151 169  51  25]
 [235 113 133  66]]
DETAILS: prints array length as the number of faces, and the index value is the number of matches
[101 155 136]


In [8]:
display('3GrilsImage', img)